### PR TITLE
Re-locate helper scripts building SOLVCON

### PR DESCRIPTION
**Pull request by tai271828**
This pull request is the follow-up implementation for the discussion https://github.com/solvcon/devenv/issues/13#issuecomment-820741629 . The namespace of the folder/file hierarchy is still open and welcome for more inputs, comments, and suggestions.

# How to Test This Pull Request
The folder hierarchy re-structuring should keep the CI working. Triiger CI to verify this pull request.

### CODE REVIEW

**Comment by tai271828** [comment]
Regarding the update of README, I noticed that `scripts/cmd.d/build.d` does not represent, and it seems a necessary component of the feature `dev build`, and `dev build` is a must step for building applications.

I could not move forward the following two items until I am sure `devenv` the management tool codebase is ready, and know how to use `bin/devenv` correctly. For example,  

- use `devenv` in `bin/build-application-solvcon-devenv.sh`
- update README to make the how-to-use details of `devenv` more comprehensive

**Comment by yungyuc** [comment]
LGTM

**Comment by yungyuc** [comment]
> Regarding the update of README, I noticed that `scripts/cmd.d/build.d` does not represent, and it seems a necessary component of the feature `dev build`, and `dev build` is a must step for building applications.
> 
> Thus, I could not move forward the following two items until I am sure `devenv` the management tool codebase is ready, and know how to use `bin/devenv` correctly:
> 
> * use `devenv` in `bin/build-application-solvcon-devenv.sh`
> * update README to make the how-to-use details of `devenv` more comprehensive

This PR looks good to me and I just merged it.  I'd like the challenges you described to be addressed but am not sure what is it.  Could you elaborate a little bit more in the [discussion board](https://github.com/solvcon/devenv/discussions)?

**Comment by yungyuc** [comment]
And sorry I forgot to approve the review before merging.  I will try to do it correctly next time.

**Comment by tai271828** [comment]
> > Regarding the update of README, I noticed that `scripts/cmd.d/build.d` does not represent, and it seems a necessary component of the feature `dev build`, and `dev build` is a must step for building applications.
> > Thus, I could not move forward the following two items until I am sure `devenv` the management tool codebase is ready, and know how to use `bin/devenv` correctly:
> > 
> > * use `devenv` in `bin/build-application-solvcon-devenv.sh`
> > * update README to make the how-to-use details of `devenv` more comprehensive
> 
> This PR looks good to me and I just merged it. I'd like the challenges you described to be addressed but am not sure what is it. Could you elaborate a little bit more in the [discussion board](https://github.com/solvcon/devenv/discussions)?

The discussion board is certainly a good place for the discussion. I have created the discussion https://github.com/solvcon/devenv/discussions/16 for the purpose.

**Pull request merged**
